import type { UnifiedBuildingLayout, UnifiedBuildingLayoutInput } from "../unifiedLayout";

export interface BuildingCountScenario {
  id: string;
  sourceId: string;
  title: string;
  note: string;
  input: UnifiedBuildingLayoutInput;
  expected: UnifiedBuildingLayout;
}

export const BUILDING_COUNT_SCENARIOS: readonly BuildingCountScenario[] = [
  {
    id: "SCN-BUILDING-COUNT-001",
    sourceId: "KM-004",
    title: "Односкатный каркас VELICAN",
    note: "Draft-сценарий: буквенные оси требуют подтверждения как основные несущие.",
    input: {
      mainFrameAxisCount: 12,
      crossSpanCount: 6,
    },
    expected: {
      frames: {
        totalFrameAxes: 12,
        interiorFrameAxes: 10,
        endFrameAxes: 2,
        frameBays: 11,
        extraFrameAxes: 0,
      },
      columns: {
        edgePerFrame: 2,
        middlePerFrame: 5,
        totalPerFrame: 7,
        hasCrane: false,
        interiorEdge: 20,
        interiorMiddle: 50,
        interiorTotal: 70,
        endEdge: 4,
        endMiddle: 10,
        endTotal: 14,
        allEdge: 24,
        allMiddle: 60,
        allTotal: 84,
        mainEdge: 20,
        mainMiddle: 50,
        mainTotal: 70,
        endFachwerkEdge: 4,
        endFachwerkMiddle: 10,
        endFachwerkTotal: 14,
      },
    },
  },
  {
    id: "SCN-BUILDING-COUNT-002",
    sourceId: "KM-006",
    title: "Двухпролётный каркас VELICAN",
    note: "Draft-сценарий: дополнительная ось 11/1 учитывается отдельно от основных рам.",
    input: {
      mainFrameAxisCount: 20,
      crossSpanCount: 2,
      extraFrameAxisCount: 1,
    },
    expected: {
      frames: {
        totalFrameAxes: 20,
        interiorFrameAxes: 18,
        endFrameAxes: 2,
        frameBays: 19,
        extraFrameAxes: 1,
      },
      columns: {
        edgePerFrame: 2,
        middlePerFrame: 1,
        totalPerFrame: 3,
        hasCrane: false,
        interiorEdge: 36,
        interiorMiddle: 18,
        interiorTotal: 54,
        endEdge: 4,
        endMiddle: 2,
        endTotal: 6,
        allEdge: 40,
        allMiddle: 20,
        allTotal: 60,
        mainEdge: 36,
        mainMiddle: 18,
        mainTotal: 54,
        endFachwerkEdge: 4,
        endFachwerkMiddle: 2,
        endFachwerkTotal: 6,
      },
    },
  },
  {
    id: "SCN-BUILDING-COUNT-002-CRANE",
    sourceId: "KM-006",
    title: "Two-span VELICAN frame with crane decision",
    note: "GIP decision: with a crane, end columns are counted as main frame columns.",
    input: {
      mainFrameAxisCount: 20,
      crossSpanCount: 2,
      extraFrameAxisCount: 1,
      hasCrane: true,
    },
    expected: {
      frames: {
        totalFrameAxes: 20,
        interiorFrameAxes: 18,
        endFrameAxes: 2,
        frameBays: 19,
        extraFrameAxes: 1,
      },
      columns: {
        edgePerFrame: 2,
        middlePerFrame: 1,
        totalPerFrame: 3,
        hasCrane: true,
        interiorEdge: 36,
        interiorMiddle: 18,
        interiorTotal: 54,
        endEdge: 4,
        endMiddle: 2,
        endTotal: 6,
        allEdge: 40,
        allMiddle: 20,
        allTotal: 60,
        mainEdge: 40,
        mainMiddle: 20,
        mainTotal: 60,
        endFachwerkEdge: 0,
        endFachwerkMiddle: 0,
        endFachwerkTotal: 0,
      },
    },
  },
  {
    id: "SCN-BUILDING-COUNT-003",
    sourceId: "KM-009",
    title: "Четырёхпролётный каркас VELICAN",
    note: "Draft-сценарий: промежуточные буквенные оси учитываются отдельно от основных.",
    input: {
      mainFrameAxisCount: 13,
      crossSpanCount: 4,
    },
    expected: {
      frames: {
        totalFrameAxes: 13,
        interiorFrameAxes: 11,
        endFrameAxes: 2,
        frameBays: 12,
        extraFrameAxes: 0,
      },
      columns: {
        edgePerFrame: 2,
        middlePerFrame: 3,
        totalPerFrame: 5,
        hasCrane: false,
        interiorEdge: 22,
        interiorMiddle: 33,
        interiorTotal: 55,
        endEdge: 4,
        endMiddle: 6,
        endTotal: 10,
        allEdge: 26,
        allMiddle: 39,
        allTotal: 65,
        mainEdge: 22,
        mainMiddle: 33,
        mainTotal: 55,
        endFachwerkEdge: 4,
        endFachwerkMiddle: 6,
        endFachwerkTotal: 10,
      },
    },
  },
];
