import { describe, expect, it } from "vitest";
import { DEFAULT_COLUMN_INPUT } from "../defaults/columnInput";
import { runCalculation } from "./engine";
import type { CalculationInput, ColumnType, SpanCount } from "./types";
import type { TerrainType } from "../types/common";
import fixtures from "./__fixtures__/column-scenarios.json";

/**
 * Acceptance test for the column engine vs frozen Excel ground truth.
 *
 * The fixture `__fixtures__/column-scenarios.json` is generated by
 * `scripts/freeze_column_fixtures.py` from `scripts/verify_baseline.py`,
 * which is the Python re-implementation of the Excel formulas validated
 * against LibreOffice-recalculated Excel with 0.00% deviation on N and M.
 * See `knowledge/log.md` for the validation history.
 *
 * Per `knowledge/AGENTS.md`: do NOT modify the fixture to make a failing
 * test pass. A drift means either the engine changed (review the change)
 * or the source Excel changed (regenerate the fixture deliberately and
 * record it in `knowledge/log.md`).
 */

interface Tolerances {
  readonly relative: number;
  readonly absolute_min: number;
}

interface ScenarioInput {
  readonly span: number;
  readonly length: number;
  readonly h: number;
  readonly slope: number;
  readonly frame_pitch: number;
  readonly fachverk_pitch: number;
  readonly spans: "one" | "multi";
  readonly ties: boolean;
  readonly terrain: "A" | "B" | "C";
  readonly col_type: ColumnType;
  readonly w0: number;
  readonly sg: number;
  readonly gamma_n: number;
  readonly addition: number;
  readonly roof_load: number;
  readonly wall_load: number;
}

interface ExpectedResult {
  readonly N_kN: number;
  readonly M_kNm: number;
  readonly snow_kPa: number;
  readonly windH_kPa: number;
  readonly windV_kPa: number;
}

interface ExcelAnchor {
  readonly N_kN: number;
  readonly M_kNm: number;
  readonly snow_kPa: number;
}

interface Scenario {
  readonly id: string;
  readonly label: string;
  readonly input: ScenarioInput;
  readonly expected: ExpectedResult;
  readonly excel_anchor?: ExcelAnchor;
}

interface FixtureFile {
  readonly tolerances: Tolerances;
  readonly scenarios: readonly Scenario[];
}

const fx = fixtures as unknown as FixtureFile;

const SPANS_MAP: Record<ScenarioInput["spans"], SpanCount> = {
  one: "single",
  multi: "multi",
};

function buildInput(s: ScenarioInput): CalculationInput {
  return {
    ...DEFAULT_COLUMN_INPUT,
    span_m: s.span,
    length_m: s.length,
    height_m: s.h,
    roofSlope_deg: s.slope,
    framePitch_m: s.frame_pitch,
    fachverkPitch_m: s.fachverk_pitch,
    spanCount: SPANS_MAP[s.spans],
    perimeterTies: s.ties,
    terrainType: s.terrain as TerrainType,
    columnType: s.col_type,
    w0_kPa: s.w0,
    Sg_kPa: s.sg,
    responsibilityCoeff: s.gamma_n,
    loadAddition_pct: s.addition,
    roofLoad_kPa: s.roof_load,
    wallLoad_kPa: s.wall_load,
  };
}

function close(actual: number, expected: number, tol: Tolerances): boolean {
  const tolerance = Math.max(Math.abs(expected) * tol.relative, tol.absolute_min);
  return Math.abs(actual - expected) <= tolerance;
}

describe("column engine — Excel acceptance (10 scenarios)", () => {
  it.each(fx.scenarios)("$id — $label", (sc) => {
    const out = runCalculation(buildInput(sc.input));

    const checks: Array<[string, number, number]> = [
      ["N_kN", out.N_kN, sc.expected.N_kN],
      ["M_kNm", out.M_kNm, sc.expected.M_kNm],
      ["snow_kPa", out.snowLoad_kPa, sc.expected.snow_kPa],
      ["windH_kPa", out.windPressure_kPa, sc.expected.windH_kPa],
      ["windV_kPa", out.windSuction_kPa, sc.expected.windV_kPa],
    ];

    for (const [name, actual, expected] of checks) {
      if (!close(actual, expected, fx.tolerances)) {
        // Build a precise message so a regression points at the
        // exact field that drifted, not just at "object mismatch".
        throw new Error(
          `${sc.id} ${name}: actual=${actual.toFixed(6)} ` +
            `expected=${expected.toFixed(6)} ` +
            `Δ=${(actual - expected).toFixed(6)} ` +
            `(rel=${fx.tolerances.relative}, abs_min=${fx.tolerances.absolute_min})`,
        );
      }
    }
  });

  it("SCN-COL-DEFAULT matches Excel-published anchors (N, M, snow)", () => {
    const sc = fx.scenarios.find((s) => s.id === "SCN-COL-DEFAULT");
    if (!sc || !sc.excel_anchor) {
      throw new Error("SCN-COL-DEFAULT must define excel_anchor");
    }
    const out = runCalculation(buildInput(sc.input));

    // Excel publishes 2 decimal places, so we compare with 0.01 absolute
    // tolerance — looser than the relative tolerance used scenario-wide
    // because we are testing against a rounded Excel display value.
    expect(out.N_kN).toBeCloseTo(sc.excel_anchor.N_kN, 1);
    expect(out.M_kNm).toBeCloseTo(sc.excel_anchor.M_kNm, 1);
    expect(out.snowLoad_kPa).toBeCloseTo(sc.excel_anchor.snow_kPa, 2);
  });

  it("returns at least one viable profile for every scenario", () => {
    // The engine must always have *some* solution for the default-style
    // inputs — empty result lists almost always indicate a regression in
    // the strength/stability checks rather than a legitimate "no profile
    // fits" outcome.
    for (const sc of fx.scenarios) {
      const out = runCalculation(buildInput(sc.input));
      expect(out.results.length, `${sc.id}: empty result set`).toBeGreaterThan(0);
    }
  });
});
